[theme]
base="dark"
primaryColor="#3498DB" ; Blue color
secondaryBackgroundColor="#2C3E50" ; Dark blue background
textColor="#FFFFFF" ; White text color for contrast
font="sans serif" ; Optional: Change the font if desired
